### ISSUE TITLE
Funktion

### ISSUE THREAD

**Issue by DickerPeter** [blitze299/bayernfahrplan-API#1]
Kurze Frage läuft die Abfrage noch mit deinen Code?

**Comment by DickerPeter** [comment]
Hallo sind Sie noch aktiv hier?

**Comment by blitze299** [comment]
Moin, ne leider habe ich das Projekt an den Nagel gehängt, weil zu kompliziert. Es gibt als Alternative eine öffentliche API direkt bei Bayernfahrplan. Den Zugang erhält mann, wenn man die anschreibt. vg
